create table public.admin_users (
  email text primary key check (email = lower(email)),
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('teclados', 'mouse', 'audifonos', 'mousepads', 'camaras', 'accesorios')),
  emoji text not null default '📦',
  name text not null check (char_length(name) between 1 and 160),
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  badge text check (badge is null or badge in ('new', 'hot')),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.offers (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete cascade,
  old_price numeric(12,2) not null check (old_price > 0),
  offer_price numeric(12,2) not null check (offer_price > 0 and offer_price < old_price),
  discount_percent integer not null check (discount_percent between 1 and 99),
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_date is null or end_date is null or start_date <= end_date)
);

create index offers_product_id_idx on public.offers(product_id);
create index offers_dates_idx on public.offers(start_date, end_date);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger offers_set_updated_at
before update on public.offers
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.products enable row level security;
alter table public.offers enable row level security;

create policy "Admins can read their authorization"
on public.admin_users
for select
to authenticated
using (lower(email) = lower((select auth.jwt()) ->> 'email'));

create policy "Users can read allowed products"
on public.products
for select
to anon, authenticated
using (
  active = true
  or exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

create policy "Admins can update products"
on public.products
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

create policy "Admins can delete products"
on public.products
for delete
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

create policy "Users can read allowed offers"
on public.offers
for select
to anon, authenticated
using (
  (
    (start_date is null or start_date <= current_date)
    and (end_date is null or end_date >= current_date)
    and exists (
      select 1
      from public.products
      where products.id = offers.product_id
        and products.active = true
    )
  )
  or exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

create policy "Admins can insert offers"
on public.offers
for insert
to authenticated
with check (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

create policy "Admins can update offers"
on public.offers
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

create policy "Admins can delete offers"
on public.offers
for delete
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where lower(email) = lower((select auth.jwt()) ->> 'email')
  )
);

revoke all on public.admin_users, public.products, public.offers from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.products, public.offers to anon;
grant select on public.admin_users to anon;
grant select on public.products, public.offers to authenticated;
grant select on public.admin_users to authenticated;
grant insert, update, delete on public.products, public.offers to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter publication supabase_realtime add table public.products;
alter publication supabase_realtime add table public.offers;

insert into public.products
  (category, emoji, name, description, price, stock, badge, image_url, active)
values
  ('teclados', '⌨️', 'Razer BlackWidow V3 RGB', 'Switches Green, Chroma RGB, 100%.', 850, 5, null, null, true),
  ('teclados', '⌨️', 'Logitech G Pro X TKL', 'Mecánico compacto, switches intercambiables.', 720, 3, 'new', null, true),
  ('teclados', '⌨️', 'Redragon K552 Mecánico', 'Switches azules, retroiluminación roja.', 285, 8, null, null, true),
  ('mouse', '🖱️', 'Logitech G502 HERO', '25.600 DPI, 11 botones, pesas ajustables.', 540, 4, null, null, true),
  ('mouse', '🖱️', 'Razer DeathAdder V3', '30K DPI, inalámbrico 90h, 64g.', 680, 2, 'new', null, true),
  ('mouse', '🖱️', 'HyperX Pulsefire Haste 2', '26K DPI, honeycomb shell, 61g ultraligero.', 390, 6, null, null, true),
  ('audifonos', '🎧', 'HyperX Cloud Alpha', 'Drivers duales, mic desmontable, 300h.', 620, 4, null, null, true),
  ('audifonos', '🎧', 'SteelSeries Arctis Nova Pro', 'Hi-Fi, ANC, swapping de batería.', 1150, 1, 'new', null, true),
  ('audifonos', '🎧', 'Razer BlackShark V2 X', '7.1 virtual, 50mm drivers, cardioide.', 380, 7, null, null, true),
  ('mousepads', '🟣', 'SteelSeries QcK Heavy XXL', '900×400mm, microtexturada, base goma.', 220, 10, null, null, true),
  ('mousepads', '🟣', 'Razer Strider XXL', 'Hybrid cloth/speed, 940×410mm, cosido.', 310, 5, 'new', null, true),
  ('mousepads', '🟣', 'Logitech G840 XL', 'Tela optimizada, antidesliz, 900×400.', 245, 6, null, null, true),
  ('camaras', '📷', 'Logitech StreamCam Plus', '1080p/60fps, autoenfoque, USB-C.', 590, 2, null, null, true),
  ('camaras', '📷', 'Razer Kiyo Pro Ultra', '4K/30fps, Sony 1/1.2, f/1.7, HDR.', 980, 1, 'new', null, true),
  ('camaras', '📷', 'Trust Taxon 2K QHD', '2560×1440, micrófono, plug & play.', 320, 5, null, null, true),
  ('accesorios', '🎮', 'Corsair MM700 RGB Extendido', 'RGB perimetral, carga Qi integrada.', 460, 3, null, null, true),
  ('accesorios', '🎮', 'Hub USB-C Gamer 7-en-1', '3×USB-A 3.0, HDMI 4K, PD 100W.', 185, 9, null, null, true),
  ('accesorios', '🎮', 'Soporte Auriculares RGB', 'Aluminio, RGB, USB, base antidesliz.', 145, 6, 'new', null, true),
  ('accesorios', '🎮', 'Controlador Xbox Series S', 'Bluetooth + USB-C, compatible PC.', 380, 4, null, null, true),
  ('accesorios', '🎮', 'Alfombrilla Carga Inalámbrica', 'Qi 10W, RGB lateral, tela suave.', 210, 5, null, null, true);

insert into public.admin_users (email)
values ('matddrchll@gmail.com');
